apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cert-dnsimple-secret
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend # The name of the basic store from external-secrets/operator
    kind: ClusterSecretStore
  target:
    name: cert-dnsimple-secret # Name of this secret
    creationPolicy: Owner
  data:
    - secretKey: token # Name of the key in the kubernetes secret
      remoteRef:
        key: external-dns
        property: oauth
