apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: dennistryy3@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          webhook:
            groupName: acme.dnsimple.com
            solverName: dnsimple
            config:
              accountID: "159380"
              tokenSecretRef:
                name: cert-dnsimple-secret
                key: token
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: dennistryy3@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          webhook:
            groupName: acme.dnsimple.com
            solverName: dnsimple
            config:
              accountID: "159380"
              tokenSecretRef:
                name: cert-dnsimple-secret
                key: token
---
# Self-signed ClusterIssuer for local domains (*.tryy3.local)
# This issuer creates self-signed certificates without requiring external validation
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
