---
# Note: This uses the same ServiceAccount as the main external-dns
# If you need separate permissions, create a new ServiceAccount instead

apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: external-dns
  labels:
    app: external-dns

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns-local
  labels:
    app: external-dns-local
rules:
  # Read services (source for DNS records)
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]

  # Read endpoints for service status
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch"]

  # Read pods for debugging
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

  # Read nodes for metadata
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]

  # Gateway API resources
  - apiGroups: ["gateway.networking.k8s.io"]
    resources:
      - "gateways"
      - "httproutes"
      - "tlsroutes"
      - "tcproutes"
      - "udproutes"
      - "grpcroutes"
    verbs: ["get", "list", "watch"]

  # Gateway API status (for updates)
  - apiGroups: ["gateway.networking.k8s.io"]
    resources:
      - "gateways/status"
      - "httproutes/status"
    verbs: ["get", "update", "patch"]

  # Networking resources (Ingress, etc.)
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-local
  labels:
    app: external-dns-local
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns-local
subjects:
  - kind: ServiceAccount
    name: external-dns
    namespace: external-dns

---
# Role for managing TXT registry records in the same namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: external-dns-local
  namespace: external-dns
  labels:
    app: external-dns-local
rules:
  # Read/Write endpoints for TXT registry
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: external-dns-local
  namespace: external-dns
  labels:
    app: external-dns-local
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: external-dns-local
subjects:
  - kind: ServiceAccount
    name: external-dns
    namespace: external-dns
