apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: longhorn-reliable
-
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-time-pvc
  labels:
    app: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-reliable
  resources:
    requests:
      storage: 1Mi
-
apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-time-pv
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /etc/localtime
  claimRef:
    name: home-assistant-time-pvc
    namespace: default
-