kind: Cluster
name: talos-default
talos:
  version: v1.11.1
kubernetes:
  version: 1.34.1
features:
  enableWorkloadProxy: true
patches:
  - name: cni
    file: patches/cni.yaml
  - name: rook-extensions
    file: patches/rook-extensions.yaml
  - name: tailscale
    file: patches/tailscale.yaml
---
kind: ControlPlane
machineClass:
  name: omni-controlplanes
  size: 2
patches:
  - name: cilium
    file: patches/cilium.yaml
  - name: argocd
    file: patches/argocd.yaml
  - name: monitoring
    file: patches/monitoring.yaml
---
kind: Workers
name: workers
machineClass:
  name: omni-workers
  size: unlimited
