apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mealie-pg
  namespace: mealie
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17

  bootstrap:
    initdb:
      database: mealie
      owner: mealie

  storage:
    storageClass: longhorn-fast
    size: 10Gi
  
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

  monitoring:
    enabled: true

  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "128MB"
      effective_cache_size: "512MB"
      maintenance_work_mem: "64MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "4MB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: "2MB"
      min_wal_size: "1GB"
      max_wal_size: "4GB"

