# TLS Certificates for Cozytemp domains
# These must be in the envoy namespace to be referenced by the Gateway

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-cozytemp-tryy3-dev
  namespace: envoy
spec:
  secretName: api-cozytemp-tryy3-dev-tls
  duration: 2160h # 90d
  renewBefore: 720h # 30d
  commonName: api.cozytemp.tryy3.dev
  dnsNames:
    - api.cozytemp.tryy3.dev
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: insights-cozytemp-tryy3-dev
  namespace: envoy
spec:
  secretName: insights-cozytemp-tryy3-dev-tls
  duration: 2160h # 90d
  renewBefore: 720h # 30d
  commonName: insights.cozytemp.tryy3.dev
  dnsNames:
    - insights.cozytemp.tryy3.dev
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-cozytemp-tryy3-dev
  namespace: envoy
spec:
  secretName: app-cozytemp-tryy3-dev-tls
  duration: 2160h # 90d
  renewBefore: 720h # 30d
  commonName: app.cozytemp.tryy3.dev
  dnsNames:
    - app.cozytemp.tryy3.dev
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

---
# Local network certificates
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-cozytemp-tryy3-local
  namespace: envoy
spec:
  secretName: api-cozytemp-tryy3-local-tls
  duration: 87600h # 10 years
  renewBefore: 720h # 30 days
  isCA: false
  privateKey:
    algorithm: RSA
    size: 2048
  commonName: api.cozytemp.tryy3.local
  dnsNames:
    - api.cozytemp.tryy3.local
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: insights-cozytemp-tryy3-local
  namespace: envoy
spec:
  secretName: insights-cozytemp-tryy3-local-tls
  duration: 87600h # 10 years
  renewBefore: 720h # 30 days
  isCA: false
  privateKey:
    algorithm: RSA
    size: 2048
  commonName: insights.cozytemp.tryy3.local
  dnsNames:
    - insights.cozytemp.tryy3.local
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-cozytemp-tryy3-local
  namespace: envoy
spec:
  secretName: app-cozytemp-tryy3-local-tls
  duration: 87600h # 10 years
  renewBefore: 720h # 30 days
  isCA: false
  privateKey:
    algorithm: RSA
    size: 2048
  commonName: app.cozytemp.tryy3.local
  dnsNames:
    - app.cozytemp.tryy3.local
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer

