apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mealie-pg
  namespace: mealie
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17

  bootstrap:
    initdb:
      database: mealie
      owner: mealie

  storage:
    storageClass: longhorn-fast
    size: 10Gi
  
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi