apiVersion: apps/v1
kind: Deployment
metadata:
  name: spoolman
  labels:
    app: spoolman
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spoolman
  template:
    metadata:
      labels:
        app: spoolman
    spec:
      containers:
        - name: spoolman
          image: ghcr.io/donkie/spoolman:0.22.1 # Do I still need to run my own version?
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
            requests:
              cpu: "25m"
              memory: "128Mi"
          ports:
            - containerPort: 8000
          env:
            - name: TZ
              value: Europe/Stockholm
            - name: EXTERNAL_DB_URL
              value: https://donkie.github.io/SpoolmanDB/
            - name: EXTERNAL_DB_SYNC_INTERVAL
              value: "120"
            - name: SPOOLMAN_LOGGING_LEVEL
              value: DEBUG
          volumeMounts:
            - name: spoolman-mount
              mountPath: /home/app/.local/share/spoolman
      volumes:
        - name: spoolman-mount
          persistentVolumeClaim:
            claimName: spoolman-data
      #imagePullSecrets:
      #  - name: harbor.tryy3.dev-registry
---
apiVersion: v1
kind: Service
metadata:
  name: spoolman-svc
spec:
  selector:
    app: spoolman
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: spoolman-pv
spec:
  capacity:
    storage: 20Gi
  nfs:
    server: 100.109.86.23
    path: /mnt/user/spoolman-data
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.2
    - rw
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spoolman-data
spec:
  # Empty storage class disables dynamic provisioning
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: spoolman-pv
