apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cozytemp-pg
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17

  bootstrap:
    initdb:
      database: app
      owner: app

  storage:
    size: 20Gi
  
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 1Gi

  monitoring:
    enabled: true