apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cozytemp-pg
  namespace: cozytemp
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17

  bootstrap:
    initdb:
      database: app
      owner: app

  storage:
    storageClass: longhorn-fast
    size: 50Gi
  
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 2Gi