# ===== HTTP ROUTES =====
# Route traffic from Tailscale gateway (tryy3.dev domains) to Kafka services
# Note: Gateway listeners are in apps/envoy/extra/

# Route 1: kafka-ui.tryy3.dev → kafka-ui:8080
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kafka-ui-route
  namespace: kafka
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: custom-domain-gateway
      namespace: envoy
      sectionName: https-kafka-ui
  hostnames:
    - "kafka-ui.tryy3.dev"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: kafka-kafka-ui
          namespace: kafka
          port: 8080

---
# Route 2: kafka.tryy3.dev → kafka-bridge:8080
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kafka-bridge-route
  namespace: kafka
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: custom-domain-gateway
      namespace: envoy
      sectionName: https-kafka
  hostnames:
    - "kafka.tryy3.dev"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: kafka-bridge-bridge-service
          namespace: kafka
          port: 8080

---
# Certificate for kafka.tryy3.dev
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kafka-tryy3-dev
  namespace: envoy
spec:
  secretName: kafka-tryy3-dev-tls
  duration: 2160h # 90d
  renewBefore: 720h # 30d
  commonName: kafka.tryy3.dev
  dnsNames:
    - kafka.tryy3.dev
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
