apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: longhorn-gateway
  namespace: longhorn-system
  labels:
    external-dns: enabled
  annotations:
    cert-manager.io/cluster-issuer: cert-manager-webhook-dnsimple-production
spec:
  gatewayClassName: tailscale
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "longhorn.tryy3.dev"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - group: ""
            kind: Secret
            name: longhorn-tryy3-dev-tls

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: longhorn-route
  namespace: longhorn-system
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: longhorn-gateway
      namespace: longhorn-system
  hostnames:
    - "longhorn.tryy3.dev"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: longhorn-frontend
          namespace: longhorn-system
          port: 80

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-tryy3-dev
  namespace: longhorn-system
spec:
  secretName: longhorn-tryy3-dev-tls
  duration: 2160h # 90d
  renewBefore: 720h # 30d
  commonName: longhorn.tryy3.dev
  dnsNames:
    - longhorn.tryy3.dev
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
